export const FETCH_REG_CORRECTO = 'FETCH_REGIS_CORRECTO'
export const FETCH_REG_ERROR = 'FETCH_REGIS_ERROR'

export const FETCH_LOGIN_CORRECTO = 'FETCH_LOGIN_CORRECTO'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'

